name: Novo teste CI com Newman

on:
  push:
    branches: [ "main" ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      - name: Run API Tests
        run: |
          mkdir -p reports
          newman run postman/orders/orders_collection.json -e postman/orders/orders_environment.json -r cli,html --reporter-html-export reports/report.html
